apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasmjs-hono
  namespace: knative-serving
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: tanjim/ec-wasmjs-hono
          imagePullPolicy: Always
